# Generated by Django 4.1.4 on 2023-01-16 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('credit_course', models.IntegerField()),
                ('semester', models.CharField(max_length=10)),
                ('clasroom', models.CharField(max_length=35)),
                ('id_career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.careers')),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_d', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close', to='Courses.hours')),
                ('cod_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.courses')),
                ('cod_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.days')),
                ('open_t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open', to='Courses.hours')),
            ],
        ),
    ]
