# Generated by Django 4.1.4 on 2023-01-23 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('credit_course', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=10)),
                ('clasroom', models.CharField(max_length=35)),
                ('id_career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.career')),
            ],
            options={
                'unique_together': {('code', 'id_career')},
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_t', models.CharField(max_length=5)),
                ('close_t', models.CharField(max_length=5)),
                ('cod_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.course')),
                ('cod_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.day')),
            ],
            options={
                'unique_together': {('cod_course', 'cod_day', 'open_t')},
            },
        ),
    ]
