# Generated by Django 4.1.4 on 2023-01-16 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_alter_times_close_t_alter_times_open_t_delete_hours'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='times',
            unique_together={('cod_course', 'cod_day')},
        ),
    ]
