# Generated by Django 4.1.4 on 2023-01-17 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_alter_times_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='times',
            unique_together={('cod_course', 'cod_day', 'open_t')},
        ),
    ]
