# Generated by Django 4.1.4 on 2023-01-17 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_button'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Careers',
            new_name='Career',
        ),
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='Days',
            new_name='Day',
        ),
        migrations.RenameModel(
            old_name='Times',
            new_name='Time',
        ),
    ]
