# Generated by Django 4.1.4 on 2023-01-17 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0006_rename_careers_career_rename_courses_course_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'id_career')},
        ),
    ]
