# Generated by Django 4.1.4 on 2023-01-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0009_rename_course2_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit_course',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='time',
            name='close_t',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='time',
            name='open_t',
            field=models.CharField(max_length=5),
        ),
    ]
